version: "3"

services:

  # Database-related

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_DB: "filesaving"

  # Service-related

  api:
    build: ./api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      # FLASK_APP: "app.py"
      # FLASK_ENV: "development"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_DB: "filesaving"
    depends_on:
      - database