version: "3"

services:

  # Database-related

  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - "9981:8080"

  database:
    image: mysql:latest
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_DATABASE: "filesaving"

  # Service-related

  api:
    build: ./api
    restart: always
    ports:
      - "9982:5000"
    volumes:
      - ./api:/code/source
      - ./notifications:/code/source/modules
    environment:
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_DATABASE: "filesaving"
      MYSQL_HOST: "database"
      NOTIFICATION_HOST: "notifications"
    depends_on:
      - database
      - notifications
  
  notifications:
    build: ./notifications
    restart: always
    ports:
      - "9983:56235"
    volumes:
      - ./notifications:/code
